### PR TITLE
Create serializer for Organizer model #7

### PR DESCRIPTION
**Pull request by rexdivakar**
- [x] Flake8 Indentation 
- [x] Added Serializer
- [x]  Added requirements.txt file

### CODE REVIEW

**Comment by rexdivakar** [comment]
Hey @gaurKrishna  Create serializer for Organizer model #7

**Comment by gaurKrishna** [comment]
> Hey @gaurKrishna Create serializer for Organizer model #7

Looks good to me, merging your pr 👍.

**Comment by rexdivakar** [comment]
Let me know if u need to build anymore stuffs!!

**Comment by rexdivakar** [comment]
Hey @gaurKrishna can you please add a label 'hacktoberfest-accepted’ else the pr wont be valid

**Comment by gaurKrishna** [comment]
> Hey @gaurKrishna can you please add a label 'hacktoberfest-accepted’ else the pr wont be valid

Done

**Pull request merged**
